// Module included in the following assemblies:
//
// * cli_reference/openshift_cli/configuring-cli.adoc

:_mod-docs-content-type: PROCEDURE
[id="cli-accessing-kubeconfig-using-cli_{context}"]
= Accessing `kubeconfig` using the `oc` CLI
include::_attributes/common-attributes.adoc[]

You can use the `oc` CLI to retrieve and configure a `kubeconfig` file for accessing your OpenShift cluster from the command line.

.Prerequisites

* You have access to the {product-title} web console or API server endpoint.
* You have a valid OpenShift user account.

.Procedure

. Log in to your OpenShift cluster by running the following command:
+
[source,terminal]
----
$ oc login <api-server-url> -u <username> -p <password>
----
+
Replace `<api-server-url>` with the full API server URL, such as `https://api.my-cluster.example.com:6443`.

. Output the current cluster configuration to a local file by running the following command:
+
[source,terminal]
----
$ oc config view --raw > kubeconfig
----

. Set the `KUBECONFIG` environment variable to point to the exported file by running the following command:
+
[source,terminal]
----
$ export KUBECONFIG=./kubeconfig
----

. You can now use `kubectl` to interact with your OpenShift cluster by running the following command:
+
[source,terminal]
----
$ kubectl get nodes
----

[NOTE]
====
If you plan to reuse the exported `kubeconfig` file across sessions or machines, store it securely and avoid committing it to source control.
====

